server:
  port: 0
spring:
    cloud:
        config:
            allowOverride: true
            failFast: true
            overrideNone: false
            overrideSystemProperties: false 
custom.property.value: 8
