server:
  port: 0

spring.h2.console.enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    password: '{cipher}4479296862ea6ad748574a960b09b2ac7f88c25842cec36edd8494e4e2289524'  #admin
